#!/usr/bin/env bash
# test/roadmap-dashboard.sh — regression lock for utils/roadmap-dashboard.sh (GH-27).

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
RENDERER="$ROOT/utils/roadmap-dashboard.sh"
ARTIFACT="$ROOT/ROADMAP-DASHBOARD.md"
SOURCE="$ROOT/ROADMAP.md"

PASS=0
FAIL=0
SKIP=0
pass() { echo "  PASS: $*"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL: $*" >&2; FAIL=$((FAIL + 1)); }
skip() { echo "  SKIP: $*"; SKIP=$((SKIP + 1)); }

echo "== test: roadmap-dashboard =="

# GH-110 P2b: ROADMAP-DASHBOARD.md is a repo-root artifact that does not travel with a vendored
# install (VENDOR_DIRS mirrors relay-automation/bin/src/utils/test/skills only). In a vendored copy
# there is nothing here to render/check, so skip the whole ROADMAP-DASHBOARD.md-dependent case
# rather than dangle-fail — mirrors the guard already landed in test/oracle-guard.sh.
if [ -e "$ARTIFACT" ]; then

out="$(bash "$RENDERER" 2>&1)"; rc=$?
if [[ $rc -eq 0 ]]; then
  pass "renderer writes the dashboard"
else
  fail "renderer exited $rc — $out"
fi

out="$(bash "$RENDERER" --check 2>&1)"; rc=$?
if [[ $rc -eq 0 ]]; then
  pass "--check passes on the committed artifact"
else
  fail "--check exited $rc — $out"
fi

if grep -qx '<!-- GENERATED by utils/roadmap-dashboard.sh — DO NOT EDIT; edit ROADMAP.md -->' "$ARTIFACT"; then
  pass "artifact carries the do-not-edit banner"
else
  fail "artifact is missing the generated banner"
fi

counts_out="$(SOURCE_PATH="$SOURCE" ARTIFACT_PATH="$ARTIFACT" node <<'NODE' 2>&1
const fs = require("fs");

const sourcePath = process.env.SOURCE_PATH;
const artifactPath = process.env.ARTIFACT_PATH;
const expectedSections = [
  "Queue / parked intake",
  "In progress",
  "Completed",
  "Deferred · vision",
];

const sourceLines = fs.readFileSync(sourcePath, "utf8").split(/\r?\n/);
const artifactLines = fs.readFileSync(artifactPath, "utf8").split(/\r?\n/);

function extractRoadmapCounts(lines) {
  const counts = {};
  let inLedger = false;
  let current = null;
  for (const section of expectedSections) counts[section] = 0;

  for (const line of lines) {
    if (!inLedger) {
      if (/^##\s+Ledger\s*$/.test(line.trim())) inLedger = true;
      continue;
    }
    if (/^##\s+/.test(line) && !/^##\s+Ledger\s*$/.test(line.trim())) break;
    const sectionMatch = line.match(/^###\s+(.+?)\s*$/);
    if (sectionMatch) {
      current = counts.hasOwnProperty(sectionMatch[1].trim()) ? sectionMatch[1].trim() : null;
      continue;
    }
    if (current && /^- \*\*/.test(line)) counts[current] += 1;
  }
  return counts;
}

function extractDashboardCounts(lines) {
  const counts = {};
  let current = null;

  for (const line of lines) {
    const sectionMatch = line.match(/^##\s+(.+?)\s*$/);
    if (sectionMatch) {
      current = sectionMatch[1].trim();
      continue;
    }
    const summaryMatch = line.match(/^Summary:\s+(\d+)\s+items\s+\|\s+Tally:/);
    if (current && summaryMatch) {
      counts[current] = Number(summaryMatch[1]);
    }
  }
  return counts;
}

const roadmapCounts = extractRoadmapCounts(sourceLines);
const dashboardCounts = extractDashboardCounts(artifactLines);

for (const section of expectedSections) {
  if (roadmapCounts[section] !== dashboardCounts[section]) {
    console.error(`${section}: roadmap=${roadmapCounts[section]} dashboard=${dashboardCounts[section]}`);
    process.exit(1);
  }
}
NODE
)"; rc=$?
if [[ $rc -eq 0 ]]; then
  pass "section counts match ROADMAP.md"
else
  fail "section counts drifted — $counts_out"
fi

else
  skip "ROADMAP-DASHBOARD.md-dependent checks need \$ROOT/ROADMAP-DASHBOARD.md (absent in a vendored copy)"
fi

echo ""
echo "  roadmap-dashboard: $PASS passed, $FAIL failed, $SKIP skipped"
[[ $FAIL -eq 0 ]] || exit 1
