#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <issue-number>"
    exit 1
fi
ISSUE_NUM="$1"

# Create and checkout fresh branch from development
git fetch origin
git checkout development
git pull origin development
BRANCH_NAME="marathon/gh-${ISSUE_NUM}-fuzz-fix"
git checkout -b "$BRANCH_NAME"

# Generate brief dynamically
mkdir -p PROJECT/2-WORKING
BRIEF_PATH="fuzz_brief_${ISSUE_NUM}.txt"
echo "# Fuzzing Target: GH-${ISSUE_NUM}" > "$BRIEF_PATH"
gh issue view "$ISSUE_NUM" >> "$BRIEF_PATH"
echo "Generated brief at $BRIEF_PATH"

# Extract artifacts dynamically using python script
echo "Extracting expected artifact paths..."
ARTIFACTS=$(python3 extract_artifacts.py "$BRIEF_PATH")

# Resolve globs in ARTIFACTS
RESOLVED_ARTIFACTS=""
IFS=',' read -ra ADDR <<< "$ARTIFACTS"
for p in "${ADDR[@]}"; do
    p=$(echo "$p" | xargs)
    for file in $p; do
        RESOLVED_ARTIFACTS="$RESOLVED_ARTIFACTS$file,"
    done
done
RESOLVED_ARTIFACTS="${RESOLVED_ARTIFACTS%,}"

export PYTHONPATH="/Users/noelsaw/Documents/GH Repos/Agent-Devtools/packages/python-sdk:$PYTHONPATH"
export AGENT_DEVTOOLS_ENABLE=1
export AGENT_DEVTOOLS_DB="/Users/noelsaw/Documents/GH Repos/fuzzing-lmstudio/.agent_devtools/trace.db"

export RELAY_TURN_TIMEOUT_S=1800

rm -rf .git/relay-driver.lock
./bin/tick release MARATHON-P1-TURN --agent agy 2>/dev/null || true
rm -rf phases/p1/* .tick/attempts/* .tick/events/* .tick/state/*

echo "Starting fuzzing loop for issue ${ISSUE_NUM} with Agy CLI (Gemini) and DevTools tracing enabled..."
if [ -n "$ARTIFACTS" ]; then
    relay-automation/marathon-drive.sh --phase-brief "$BRIEF_PATH" --artifact "$RESOLVED_ARTIFACTS" --builder agy --reviewer codex --round-cap 10
else
    echo "Warning: No artifacts extracted, running without --artifact."
    relay-automation/marathon-drive.sh --phase-brief "$BRIEF_PATH" --builder agy --reviewer codex --round-cap 10
fi

DRIVE_EXIT=$?

if [ $DRIVE_EXIT -eq 0 ]; then
    echo "marathon-drive succeeded! Creating PR..."
    # Commit the brief so working tree is clean
    rm "$BRIEF_PATH"
    
    # Push branch and create PR
    git push -u origin "$BRANCH_NAME"
    gh pr create --title "Fix: GH-${ISSUE_NUM}" --body "Automated fix for #${ISSUE_NUM} generated by Agy (Gemini 2.5 Pro) + Codex fuzzing pipeline."
    echo "PR successfully created."
else
    echo "marathon-drive failed with exit code $DRIVE_EXIT. Escalating for manual review."
    rm "$BRIEF_PATH"
    exit $DRIVE_EXIT
fi
