BEGIN TRANSACTION;
CREATE TABLE blog_stories (
            story_id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            slug TEXT NOT NULL UNIQUE,
            theme TEXT NOT NULL,
            source_evaluations TEXT NOT NULL,
            story_metadata TEXT,
            markdown_content TEXT NOT NULL,
            published_at DATETIME,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "blog_stories" VALUES('story-20260823051437','Frontier 1M Context Reasoning in Autonomous Codebases','frontier-reasoning-1m','Frontier 1M Context Reasoning in Autonomous Codebases','[]',NULL,'# Frontier 1M Context Reasoning in Autonomous Codebases

**Generated by:** `utils/py/harness_app.py blog gen` | **Published:** 2026-08-23

## Executive Summary & Empirical Takeaways

This benchmark analysis synthesizes empirical results across 1 verified agent evaluations under load in `XYZ-forge`.

## Evaluated Performance Matrix

| Task Scope | Harness & Model | Reasoning Level | Duration | Gate Passed | Grade |
|---|---|:---:|:---:|:---:|:---:|
| GH-174 test invocation | `dsh` + `deepseek/deepseek-v4-pro` | `high` | 0.0s | ✅ PASS | **A** |

## In-Depth Architectural Narratives & Field Notes

### Case Study: `deepseek/deepseek-v4-pro` on `GH-174 test invocation`
DeepSeek V4 Pro resolved the test task with high reasoning effort and zero diff regressions. Model demonstrated strong architectural adherence and minimal token consumption.

','2026-08-23 05:14:37','2026-08-23 05:14:37');
INSERT INTO "blog_stories" VALUES('story-20260824171648','Frontier AI Benchmarks in XYZ','frontier-benchmarks','Frontier AI Benchmarks in XYZ','[]',NULL,'# Frontier AI Benchmarks in XYZ

**Generated by:** `utils/py/harness_app.py blog gen` | **Published:** 2026-08-24

## Executive Summary & Empirical Takeaways

This benchmark analysis synthesizes empirical results across 17 verified agent evaluations under load in `XYZ-forge`.

## Evaluated Performance Matrix

| Task Scope | Harness & Model | Reasoning Level | Duration | Gate Passed | Grade |
|---|---|:---:|:---:|:---:|:---:|
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation | `dsh` + `deepseek/deepseek-v4-pro` | `high` | 0.0s | ✅ PASS | **A** |

## In-Depth Architectural Narratives & Field Notes

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `deepseek/deepseek-v4-pro` on `GH-174 test invocation`
DeepSeek V4 Pro resolved the test task with high reasoning effort and zero diff regressions. Model demonstrated strong architectural adherence and minimal token consumption.

','2026-08-24 17:16:48','2026-08-24 17:16:48');
CREATE TABLE devices (
            device_id TEXT PRIMARY KEY,
            user_name TEXT NOT NULL,
            os_version TEXT NOT NULL,
            cpu_cores INTEGER NOT NULL,
            ram_gb INTEGER NOT NULL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "devices" VALUES('primary-macbook-host','noelsaw1','macOS 15.6',16,64,'2026-08-23 05:14:09');
INSERT INTO "devices" VALUES('noels-Mac-Studio.local','noelsaw','darwin',10,16,'2026-08-23 05:14:35');
CREATE TABLE evaluations (
            evaluation_id TEXT PRIMARY KEY,
            invocation_id TEXT UNIQUE NOT NULL REFERENCES invocation_logs(invocation_id),
            evaluated_by TEXT NOT NULL,
            evaluation_role TEXT NOT NULL,
            grade TEXT NOT NULL CHECK(grade IN ('A', 'A-', 'B+', 'B', 'B-', 'C', 'N/A')),
            qualifying_gate_passed INTEGER NOT NULL,
            diff_cleanliness_score INTEGER,
            seam_reliability_score INTEGER,
            work_description_narrative TEXT NOT NULL,
            failure_mode_tag TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "evaluations" VALUES('eval-20260823051435-ea7c0001','inv-20260823051435-4516bcff','claude-orchestrator','Autonomous Builder','A',1,5,5,'DeepSeek V4 Pro resolved the test task with high reasoning effort and zero diff regressions. Model demonstrated strong architectural adherence and minimal token consumption.','none','2026-08-23 05:14:35');
INSERT INTO "evaluations" VALUES('eval-20260823051453-21bd23b3','inv-20260823051453-4e8404cc','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-23 05:14:53');
INSERT INTO "evaluations" VALUES('eval-20260823051938-61c94589','inv-20260823051938-5503cd42','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-23 05:19:38');
INSERT INTO "evaluations" VALUES('eval-20260823052735-b5b1a9d0','inv-20260823052735-1224170d','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-23 05:27:35');
INSERT INTO "evaluations" VALUES('eval-20260823060029-ff3f3a13','inv-20260823060029-30a72252','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-23 06:00:29');
INSERT INTO "evaluations" VALUES('eval-20260823061047-782083c7','inv-20260823061047-92186dfb','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-23 06:10:47');
INSERT INTO "evaluations" VALUES('eval-20260823160640-fc8f8d4f','inv-20260823160640-2edc54e8','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-23 16:06:40');
INSERT INTO "evaluations" VALUES('eval-20260824032347-51c3c1dd','inv-20260824032347-52900db4','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 03:23:47');
INSERT INTO "evaluations" VALUES('eval-20260824032851-e4511cd8','inv-20260824032851-36e85150','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 03:28:51');
INSERT INTO "evaluations" VALUES('eval-20260824033350-51103189','inv-20260824033350-df84a4d2','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 03:33:50');
INSERT INTO "evaluations" VALUES('eval-20260824155051-75422c72','inv-20260824155051-143eeacd','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 15:50:51');
INSERT INTO "evaluations" VALUES('eval-20260824155716-b3ec7cf0','inv-20260824155716-7d24f3df','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 15:57:16');
INSERT INTO "evaluations" VALUES('eval-20260824161219-569c9217','inv-20260824161219-14392c3e','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 16:12:19');
INSERT INTO "evaluations" VALUES('eval-20260824161917-d97f1794','inv-20260824161917-efc73541','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 16:19:17');
INSERT INTO "evaluations" VALUES('eval-20260824163612-4ed1e918','inv-20260824163612-1186c33a','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 16:36:12');
INSERT INTO "evaluations" VALUES('eval-20260824164412-599e593d','inv-20260824164412-d06593cc','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 16:44:12');
INSERT INTO "evaluations" VALUES('eval-20260824171648-aa672ae8','inv-20260824171648-b49954f1','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-24 17:16:48');
CREATE TABLE harnesses (
            harness_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            execution_engine TEXT NOT NULL,
            supports_programmatic INTEGER DEFAULT 0,
            supports_reasoning_effort INTEGER DEFAULT 1,
            headless_command_template TEXT NOT NULL,
            standing_policy_role TEXT,
            operating_constraint TEXT
        );
INSERT INTO "harnesses" VALUES('dsh','DeepSeek Harness','node_cordis',1,1,'DSH_PERMISSION_MODE=danger-full-access node .../apps/cli/lib/bin.js --profile headless --patch {overlay} "{task}"','Autonomous Headless Builder','Evaluated across 4 repository bugs with zero intervention.');
INSERT INTO "harnesses" VALUES('commandcode','Command Code','node_langbase',1,1,'cmd -p --tools-all --yolo -t "{task}"','Builder & Systems Reviewer','Requires worktree isolation and timeout bounding.');
INSERT INTO "harnesses" VALUES('codex','Codex CLI','native_cli',0,1,'codex exec "{task}"','Cost-blind default builder and reviewer','Subscription authenticated.');
INSERT INTO "harnesses" VALUES('agy','Antigravity CLI','native_cli',0,1,'agy -p "{task}"','Cost-blind cross-model builder/reviewer','Sandbox-off required; check empty exit-0.');
INSERT INTO "harnesses" VALUES('claude','Claude Code','native_cli',0,1,'claude -p "{task}"','Orchestrator and final reviewer','Do not use as default headless builder.');
INSERT INTO "harnesses" VALUES('aider','Aider','python_litellm',0,0,'aider --message "{task}"','Builder only','Force AIDER_FLAGS=--edit-format diff; reviewer seam Intermittent.');
INSERT INTO "harnesses" VALUES('pi','Pi Agent','node_multi',0,0,'pi -p --mode json "{task}"','Builder only','Explicit PI_MODEL required.');
CREATE TABLE invocation_logs (
            invocation_id TEXT PRIMARY KEY,
            device_id TEXT NOT NULL REFERENCES devices(device_id),
            harness_id TEXT NOT NULL REFERENCES harnesses(harness_id),
            model_id TEXT NOT NULL REFERENCES models(model_id),
            gateway TEXT NOT NULL,
            reasoning_effort TEXT,
            entry_point_shim TEXT NOT NULL,
            cli_flags TEXT NOT NULL,
            task_scope TEXT NOT NULL,
            wall_clock_seconds REAL,
            exit_code INTEGER NOT NULL,
            total_tokens INTEGER,
            prompt_tokens INTEGER,
            completion_tokens INTEGER,
            estimated_cost_usd REAL,
            repo_diff_stat TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "invocation_logs" VALUES('inv-20260823051435-4516bcff','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','GH-174 test invocation',0.0,0,1500,NULL,NULL,0.0012,'0 files changed','2026-08-23 05:14:35');
INSERT INTO "invocation_logs" VALUES('inv-20260823051453-4e8404cc','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,'0 files changed','2026-08-23 05:14:53');
INSERT INTO "invocation_logs" VALUES('inv-20260823051938-5503cd42','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 1 file changed, 1 insertion(+)','2026-08-23 05:19:38');
INSERT INTO "invocation_logs" VALUES('inv-20260823052735-1224170d','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 8 files changed, 42 insertions(+), 36 deletions(-)','2026-08-23 05:27:35');
INSERT INTO "invocation_logs" VALUES('inv-20260823060029-30a72252','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,'0 files changed','2026-08-23 06:00:29');
INSERT INTO "invocation_logs" VALUES('inv-20260823061047-92186dfb','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 4 files changed, 20 insertions(+), 4 deletions(-)','2026-08-23 06:10:47');
INSERT INTO "invocation_logs" VALUES('inv-20260823160640-2edc54e8','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 4 files changed, 36 insertions(+), 4 deletions(-)','2026-08-23 16:06:40');
INSERT INTO "invocation_logs" VALUES('inv-20260824032347-52900db4','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 4 files changed, 52 insertions(+), 4 deletions(-)','2026-08-24 03:23:47');
INSERT INTO "invocation_logs" VALUES('inv-20260824032844-31e597cb','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-good',0.0,0,0,NULL,NULL,0.0,' 10 files changed, 94 insertions(+), 11 deletions(-)','2026-08-24 03:28:44');
INSERT INTO "invocation_logs" VALUES('inv-20260824032845-3e2a6ec0','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-empty',0.0,5,0,NULL,NULL,0.0,' 10 files changed, 95 insertions(+), 11 deletions(-)','2026-08-24 03:28:45');
INSERT INTO "invocation_logs" VALUES('inv-20260824032846-57a5efa2','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-fail',0.0,1,0,NULL,NULL,0.0,' 10 files changed, 96 insertions(+), 11 deletions(-)','2026-08-24 03:28:46');
INSERT INTO "invocation_logs" VALUES('inv-20260824032848-8ec72a57','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-badwt',0.0,6,0,NULL,NULL,0.0,' 10 files changed, 97 insertions(+), 11 deletions(-)','2026-08-24 03:28:48');
INSERT INTO "invocation_logs" VALUES('inv-20260824032851-36e85150','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 10 files changed, 98 insertions(+), 11 deletions(-)','2026-08-24 03:28:51');
INSERT INTO "invocation_logs" VALUES('inv-20260824033342-c3034e99','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-good',0.0,0,0,NULL,NULL,0.0,'0 files changed','2026-08-24 03:33:42');
INSERT INTO "invocation_logs" VALUES('inv-20260824033343-25bf8797','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-empty',0.0,5,0,NULL,NULL,0.0,' 2 files changed, 1 insertion(+)','2026-08-24 03:33:43');
INSERT INTO "invocation_logs" VALUES('inv-20260824033346-1c08fbab','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-fail',0.0,1,0,NULL,NULL,0.0,' 2 files changed, 2 insertions(+)','2026-08-24 03:33:46');
INSERT INTO "invocation_logs" VALUES('inv-20260824033347-c8829ee2','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-badwt',0.0,6,0,NULL,NULL,0.0,' 2 files changed, 3 insertions(+)','2026-08-24 03:33:47');
INSERT INTO "invocation_logs" VALUES('inv-20260824033350-df84a4d2','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 2 files changed, 4 insertions(+)','2026-08-24 03:33:50');
INSERT INTO "invocation_logs" VALUES('inv-20260824155045-8142ada1','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-good',0.0,0,0,NULL,NULL,0.0,' 4 files changed, 24 insertions(+), 4 deletions(-)','2026-08-24 15:50:45');
INSERT INTO "invocation_logs" VALUES('inv-20260824155046-b88c9879','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-empty',0.0,5,0,NULL,NULL,0.0,' 4 files changed, 25 insertions(+), 4 deletions(-)','2026-08-24 15:50:46');
INSERT INTO "invocation_logs" VALUES('inv-20260824155047-e2c2f0ac','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-fail',0.0,1,0,NULL,NULL,0.0,' 4 files changed, 26 insertions(+), 4 deletions(-)','2026-08-24 15:50:47');
INSERT INTO "invocation_logs" VALUES('inv-20260824155048-9c51574d','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-badwt',0.0,6,0,NULL,NULL,0.0,' 4 files changed, 27 insertions(+), 4 deletions(-)','2026-08-24 15:50:48');
INSERT INTO "invocation_logs" VALUES('inv-20260824155051-143eeacd','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 4 files changed, 28 insertions(+), 4 deletions(-)','2026-08-24 15:50:51');
INSERT INTO "invocation_logs" VALUES('inv-20260824155710-4c7f27ce','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-good',0.0,0,0,NULL,NULL,0.0,'0 files changed','2026-08-24 15:57:10');
INSERT INTO "invocation_logs" VALUES('inv-20260824155711-35d01637','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-empty',0.0,5,0,NULL,NULL,0.0,' 2 files changed, 1 insertion(+)','2026-08-24 15:57:11');
INSERT INTO "invocation_logs" VALUES('inv-20260824155713-92f81282','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-fail',0.0,1,0,NULL,NULL,0.0,' 2 files changed, 2 insertions(+)','2026-08-24 15:57:13');
INSERT INTO "invocation_logs" VALUES('inv-20260824155714-d87c002c','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-badwt',0.0,6,0,NULL,NULL,0.0,' 2 files changed, 3 insertions(+)','2026-08-24 15:57:14');
INSERT INTO "invocation_logs" VALUES('inv-20260824155716-7d24f3df','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 2 files changed, 4 insertions(+)','2026-08-24 15:57:16');
INSERT INTO "invocation_logs" VALUES('inv-20260824161213-9950260a','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-good',0.0,0,0,NULL,NULL,0.0,' 1 file changed, 1 insertion(+), 1 deletion(-)','2026-08-24 16:12:13');
INSERT INTO "invocation_logs" VALUES('inv-20260824161213-b9654650','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-empty',0.0,5,0,NULL,NULL,0.0,' 3 files changed, 2 insertions(+), 1 deletion(-)','2026-08-24 16:12:13');
INSERT INTO "invocation_logs" VALUES('inv-20260824161215-a29adc7c','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-fail',0.0,1,0,NULL,NULL,0.0,' 3 files changed, 3 insertions(+), 1 deletion(-)','2026-08-24 16:12:15');
INSERT INTO "invocation_logs" VALUES('inv-20260824161216-5fcfcc06','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-badwt',0.0,6,0,NULL,NULL,0.0,' 3 files changed, 4 insertions(+), 1 deletion(-)','2026-08-24 16:12:16');
INSERT INTO "invocation_logs" VALUES('inv-20260824161219-14392c3e','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 3 files changed, 5 insertions(+), 1 deletion(-)','2026-08-24 16:12:19');
INSERT INTO "invocation_logs" VALUES('inv-20260824161911-a024eb14','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-good',0.0,0,0,NULL,NULL,0.0,' 5 files changed, 25 insertions(+), 5 deletions(-)','2026-08-24 16:19:11');
INSERT INTO "invocation_logs" VALUES('inv-20260824161912-212f2d58','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-empty',0.0,5,0,NULL,NULL,0.0,' 5 files changed, 26 insertions(+), 5 deletions(-)','2026-08-24 16:19:12');
INSERT INTO "invocation_logs" VALUES('inv-20260824161913-acec5ea3','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-fail',0.0,1,0,NULL,NULL,0.0,' 5 files changed, 27 insertions(+), 5 deletions(-)','2026-08-24 16:19:13');
INSERT INTO "invocation_logs" VALUES('inv-20260824161914-110ebf67','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-badwt',0.0,6,0,NULL,NULL,0.0,' 5 files changed, 28 insertions(+), 5 deletions(-)','2026-08-24 16:19:14');
INSERT INTO "invocation_logs" VALUES('inv-20260824161917-efc73541','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 5 files changed, 29 insertions(+), 5 deletions(-)','2026-08-24 16:19:17');
INSERT INTO "invocation_logs" VALUES('inv-20260824163606-d2c33513','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-good',0.0,0,0,NULL,NULL,0.0,'0 files changed','2026-08-24 16:36:06');
INSERT INTO "invocation_logs" VALUES('inv-20260824163607-1358ad77','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-empty',0.0,5,0,NULL,NULL,0.0,' 2 files changed, 1 insertion(+)','2026-08-24 16:36:07');
INSERT INTO "invocation_logs" VALUES('inv-20260824163608-f4a17197','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-fail',0.0,1,0,NULL,NULL,0.0,' 2 files changed, 2 insertions(+)','2026-08-24 16:36:08');
INSERT INTO "invocation_logs" VALUES('inv-20260824163609-97674293','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-badwt',0.0,6,0,NULL,NULL,0.0,' 2 files changed, 3 insertions(+)','2026-08-24 16:36:09');
INSERT INTO "invocation_logs" VALUES('inv-20260824163612-1186c33a','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 2 files changed, 4 insertions(+)','2026-08-24 16:36:12');
INSERT INTO "invocation_logs" VALUES('inv-20260824164407-58626930','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-good',0.0,0,0,NULL,NULL,0.0,' 4 files changed, 24 insertions(+), 4 deletions(-)','2026-08-24 16:44:07');
INSERT INTO "invocation_logs" VALUES('inv-20260824164408-965d0d09','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-empty',0.0,5,0,NULL,NULL,0.0,' 4 files changed, 25 insertions(+), 4 deletions(-)','2026-08-24 16:44:08');
INSERT INTO "invocation_logs" VALUES('inv-20260824164409-4bc16604','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-fail',0.0,1,0,NULL,NULL,0.0,' 4 files changed, 26 insertions(+), 4 deletions(-)','2026-08-24 16:44:09');
INSERT INTO "invocation_logs" VALUES('inv-20260824164410-31f4a381','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-badwt',0.0,6,0,NULL,NULL,0.0,' 4 files changed, 27 insertions(+), 4 deletions(-)','2026-08-24 16:44:10');
INSERT INTO "invocation_logs" VALUES('inv-20260824164412-d06593cc','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 4 files changed, 28 insertions(+), 4 deletions(-)','2026-08-24 16:44:12');
INSERT INTO "invocation_logs" VALUES('inv-20260824171642-64917be2','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-good',0.0,0,0,NULL,NULL,0.0,' 4 files changed, 44 insertions(+), 4 deletions(-)','2026-08-24 17:16:42');
INSERT INTO "invocation_logs" VALUES('inv-20260824171643-b55e26fd','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-empty',0.0,5,0,NULL,NULL,0.0,' 4 files changed, 45 insertions(+), 4 deletions(-)','2026-08-24 17:16:43');
INSERT INTO "invocation_logs" VALUES('inv-20260824171644-4fb79171','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-fail',0.0,1,0,NULL,NULL,0.0,' 4 files changed, 46 insertions(+), 4 deletions(-)','2026-08-24 17:16:44');
INSERT INTO "invocation_logs" VALUES('inv-20260824171645-d5b2b229','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','T-badwt',0.0,6,0,NULL,NULL,0.0,' 4 files changed, 47 insertions(+), 4 deletions(-)','2026-08-24 17:16:45');
INSERT INTO "invocation_logs" VALUES('inv-20260824171648-b49954f1','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 4 files changed, 48 insertions(+), 4 deletions(-)','2026-08-24 17:16:48');
CREATE TABLE models (
            model_id TEXT PRIMARY KEY,
            lab TEXT NOT NULL,
            canonical_name TEXT NOT NULL,
            gateway TEXT NOT NULL,
            context_window INTEGER NOT NULL,
            prompt_price_per_m REAL,
            completion_price_per_m REAL,
            cache_read_price_per_m REAL,
            supported_reasoning_levels TEXT,
            is_deprecated INTEGER DEFAULT 0
        );
INSERT INTO "models" VALUES('openrouter/deepseek/deepseek-v4-pro','DeepSeek','DeepSeek V4 Pro','openrouter',1000000,0.435,0.87,0.0036,'["low", "medium", "high", "max"]',0);
INSERT INTO "models" VALUES('deepseek/deepseek-chat','DeepSeek','DeepSeek V3','openrouter',1000000,0.27,1.1,0.0028,'["none"]',0);
INSERT INTO "models" VALUES('Qwen/Qwen3.8-Max','Alibaba','Qwen 3.8-Max','openrouter',1000000,2.0,6.0,0.25,'["low", "medium", "xhigh"]',0);
INSERT INTO "models" VALUES('Qwen/Qwen3.7-Flash','Alibaba','Qwen 3.7-Flash','openrouter',1000000,0.03,0.13,0.006,'["none"]',0);
INSERT INTO "models" VALUES('openrouter/stealth/ox-alpha','Stealth','Stealth Ox-Alpha','openrouter',1000000,1.5,4.5,0.2,'["high", "max"]',0);
INSERT INTO "models" VALUES('zai-org/GLM-5.3','Z.ai','GLM 5.3 High','openrouter',1000000,1.4,4.4,0.26,'["low", "high", "max"]',0);
INSERT INTO "models" VALUES('google/gemma-4-31b-qat','Google','Gemma 4 31B QAT','lmstudio',32768,0.0,0.0,0.0,'["none"]',0);
INSERT INTO "models" VALUES('deepseek/deepseek-v4-pro','Auto','deepseek/deepseek-v4-pro','openrouter',1000000,0.0,0.0,0.0,'["none"]',0);
CREATE TABLE user_configs (
            config_id TEXT PRIMARY KEY,
            device_id TEXT NOT NULL REFERENCES devices(device_id),
            default_harness TEXT NOT NULL,
            default_gateway TEXT NOT NULL,
            default_model TEXT NOT NULL,
            default_reasoning_effort TEXT,
            is_active INTEGER DEFAULT 1,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "user_configs" VALUES('cfg-primary-default','primary-macbook-host','deepseek-harness','openrouter','deepseek/deepseek-v4-pro','high',1,'2026-08-23 05:14:09');
CREATE INDEX idx_invocation_device ON invocation_logs(device_id);
CREATE INDEX idx_invocation_harness ON invocation_logs(harness_id);
CREATE INDEX idx_invocation_model ON invocation_logs(model_id);
CREATE INDEX idx_eval_grade ON evaluations(grade);
COMMIT;
