BEGIN TRANSACTION;
CREATE TABLE blog_stories (
            story_id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            slug TEXT NOT NULL UNIQUE,
            theme TEXT NOT NULL,
            source_evaluations TEXT NOT NULL,
            story_metadata TEXT,
            markdown_content TEXT NOT NULL,
            published_at DATETIME,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "blog_stories" VALUES('story-20260823051437','Frontier 1M Context Reasoning in Autonomous Codebases','frontier-reasoning-1m','Frontier 1M Context Reasoning in Autonomous Codebases','[]',NULL,'# Frontier 1M Context Reasoning in Autonomous Codebases

**Generated by:** `utils/py/harness_app.py blog gen` | **Published:** 2026-08-23

## Executive Summary & Empirical Takeaways

This benchmark analysis synthesizes empirical results across 1 verified agent evaluations under load in `XYZ-forge`.

## Evaluated Performance Matrix

| Task Scope | Harness & Model | Reasoning Level | Duration | Gate Passed | Grade |
|---|---|:---:|:---:|:---:|:---:|
| GH-174 test invocation | `dsh` + `deepseek/deepseek-v4-pro` | `high` | 0.0s | ✅ PASS | **A** |

## In-Depth Architectural Narratives & Field Notes

### Case Study: `deepseek/deepseek-v4-pro` on `GH-174 test invocation`
DeepSeek V4 Pro resolved the test task with high reasoning effort and zero diff regressions. Model demonstrated strong architectural adherence and minimal token consumption.

','2026-08-23 05:14:37','2026-08-23 05:14:37');
INSERT INTO "blog_stories" VALUES('story-20260823052735','Frontier AI Benchmarks in XYZ','frontier-benchmarks','Frontier AI Benchmarks in XYZ','[]',NULL,'# Frontier AI Benchmarks in XYZ

**Generated by:** `utils/py/harness_app.py blog gen` | **Published:** 2026-08-23

## Executive Summary & Empirical Takeaways

This benchmark analysis synthesizes empirical results across 4 verified agent evaluations under load in `XYZ-forge`.

## Evaluated Performance Matrix

| Task Scope | Harness & Model | Reasoning Level | Duration | Gate Passed | Grade |
|---|---|:---:|:---:|:---:|:---:|
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation in sandbox | `commandcode` + `Qwen/Qwen3.8-Max` | `xhigh` | 0.0s | ✅ PASS | **A-** |
| GH-174 test invocation | `dsh` + `deepseek/deepseek-v4-pro` | `high` | 0.0s | ✅ PASS | **A** |

## In-Depth Architectural Narratives & Field Notes

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `Qwen/Qwen3.8-Max` on `GH-174 test invocation in sandbox`
Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.

### Case Study: `deepseek/deepseek-v4-pro` on `GH-174 test invocation`
DeepSeek V4 Pro resolved the test task with high reasoning effort and zero diff regressions. Model demonstrated strong architectural adherence and minimal token consumption.

','2026-08-23 05:27:35','2026-08-23 05:27:35');
CREATE TABLE devices (
            device_id TEXT PRIMARY KEY,
            user_name TEXT NOT NULL,
            os_version TEXT NOT NULL,
            cpu_cores INTEGER NOT NULL,
            ram_gb INTEGER NOT NULL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "devices" VALUES('primary-macbook-host','noelsaw1','macOS 15.6',16,64,'2026-08-23 05:14:09');
INSERT INTO "devices" VALUES('noels-Mac-Studio.local','noelsaw','darwin',10,16,'2026-08-23 05:14:35');
CREATE TABLE evaluations (
            evaluation_id TEXT PRIMARY KEY,
            invocation_id TEXT UNIQUE NOT NULL REFERENCES invocation_logs(invocation_id),
            evaluated_by TEXT NOT NULL,
            evaluation_role TEXT NOT NULL,
            grade TEXT NOT NULL CHECK(grade IN ('A', 'A-', 'B+', 'B', 'B-', 'C', 'N/A')),
            qualifying_gate_passed INTEGER NOT NULL,
            diff_cleanliness_score INTEGER,
            seam_reliability_score INTEGER,
            work_description_narrative TEXT NOT NULL,
            failure_mode_tag TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "evaluations" VALUES('eval-20260823051435-ea7c0001','inv-20260823051435-4516bcff','claude-orchestrator','Autonomous Builder','A',1,5,5,'DeepSeek V4 Pro resolved the test task with high reasoning effort and zero diff regressions. Model demonstrated strong architectural adherence and minimal token consumption.','none','2026-08-23 05:14:35');
INSERT INTO "evaluations" VALUES('eval-20260823051453-21bd23b3','inv-20260823051453-4e8404cc','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-23 05:14:53');
INSERT INTO "evaluations" VALUES('eval-20260823051938-61c94589','inv-20260823051938-5503cd42','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-23 05:19:38');
INSERT INTO "evaluations" VALUES('eval-20260823052735-b5b1a9d0','inv-20260823052735-1224170d','stealth/ox-alpha','Systems Reviewer','A-',1,5,5,'Qwen 3.8-Max executed thorough systems refactoring with extra high reasoning effort.','none','2026-08-23 05:27:35');
CREATE TABLE harnesses (
            harness_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            execution_engine TEXT NOT NULL,
            supports_programmatic INTEGER DEFAULT 0,
            supports_reasoning_effort INTEGER DEFAULT 1,
            headless_command_template TEXT NOT NULL,
            standing_policy_role TEXT,
            operating_constraint TEXT
        );
INSERT INTO "harnesses" VALUES('dsh','DeepSeek Harness','node_cordis',1,1,'DSH_PERMISSION_MODE=danger-full-access node .../apps/cli/lib/bin.js --profile headless --patch {overlay} "{task}"','Autonomous Headless Builder','Evaluated across 4 repository bugs with zero intervention.');
INSERT INTO "harnesses" VALUES('commandcode','Command Code','node_langbase',1,1,'cmd -p --tools-all --yolo -t "{task}"','Builder & Systems Reviewer','Requires worktree isolation and timeout bounding.');
INSERT INTO "harnesses" VALUES('codex','Codex CLI','native_cli',0,1,'codex exec "{task}"','Cost-blind default builder and reviewer','Subscription authenticated.');
INSERT INTO "harnesses" VALUES('agy','Antigravity CLI','native_cli',0,1,'agy -p "{task}"','Cost-blind cross-model builder/reviewer','Sandbox-off required; check empty exit-0.');
INSERT INTO "harnesses" VALUES('claude','Claude Code','native_cli',0,1,'claude -p "{task}"','Orchestrator and final reviewer','Do not use as default headless builder.');
INSERT INTO "harnesses" VALUES('aider','Aider','python_litellm',0,0,'aider --message "{task}"','Builder only','Force AIDER_FLAGS=--edit-format diff; reviewer seam Intermittent.');
INSERT INTO "harnesses" VALUES('pi','Pi Agent','node_multi',0,0,'pi -p --mode json "{task}"','Builder only','Explicit PI_MODEL required.');
CREATE TABLE invocation_logs (
            invocation_id TEXT PRIMARY KEY,
            device_id TEXT NOT NULL REFERENCES devices(device_id),
            harness_id TEXT NOT NULL REFERENCES harnesses(harness_id),
            model_id TEXT NOT NULL REFERENCES models(model_id),
            gateway TEXT NOT NULL,
            reasoning_effort TEXT,
            entry_point_shim TEXT NOT NULL,
            cli_flags TEXT NOT NULL,
            task_scope TEXT NOT NULL,
            wall_clock_seconds REAL,
            exit_code INTEGER NOT NULL,
            total_tokens INTEGER,
            prompt_tokens INTEGER,
            completion_tokens INTEGER,
            estimated_cost_usd REAL,
            repo_diff_stat TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "invocation_logs" VALUES('inv-20260823051435-4516bcff','noels-Mac-Studio.local','dsh','deepseek/deepseek-v4-pro','openrouter','high','deepseek-turn.py','[]','GH-174 test invocation',0.0,0,1500,NULL,NULL,0.0012,'0 files changed','2026-08-23 05:14:35');
INSERT INTO "invocation_logs" VALUES('inv-20260823051453-4e8404cc','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,'0 files changed','2026-08-23 05:14:53');
INSERT INTO "invocation_logs" VALUES('inv-20260823051938-5503cd42','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 1 file changed, 1 insertion(+)','2026-08-23 05:19:38');
INSERT INTO "invocation_logs" VALUES('inv-20260823052735-1224170d','noels-Mac-Studio.local','commandcode','Qwen/Qwen3.8-Max','openrouter','xhigh','commandcode-turn.sh','[]','GH-174 test invocation in sandbox',0.0,0,3200,NULL,NULL,0.0064,' 8 files changed, 42 insertions(+), 36 deletions(-)','2026-08-23 05:27:35');
CREATE TABLE models (
            model_id TEXT PRIMARY KEY,
            lab TEXT NOT NULL,
            canonical_name TEXT NOT NULL,
            gateway TEXT NOT NULL,
            context_window INTEGER NOT NULL,
            prompt_price_per_m REAL,
            completion_price_per_m REAL,
            cache_read_price_per_m REAL,
            supported_reasoning_levels TEXT,
            is_deprecated INTEGER DEFAULT 0
        );
INSERT INTO "models" VALUES('openrouter/deepseek/deepseek-v4-pro','DeepSeek','DeepSeek V4 Pro','openrouter',1000000,0.435,0.87,0.0036,'["low", "medium", "high", "max"]',0);
INSERT INTO "models" VALUES('deepseek/deepseek-chat','DeepSeek','DeepSeek V3','openrouter',1000000,0.27,1.1,0.0028,'["none"]',0);
INSERT INTO "models" VALUES('Qwen/Qwen3.8-Max','Alibaba','Qwen 3.8-Max','openrouter',1000000,2.0,6.0,0.25,'["low", "medium", "xhigh"]',0);
INSERT INTO "models" VALUES('Qwen/Qwen3.7-Flash','Alibaba','Qwen 3.7-Flash','openrouter',1000000,0.03,0.13,0.006,'["none"]',0);
INSERT INTO "models" VALUES('openrouter/stealth/ox-alpha','Stealth','Stealth Ox-Alpha','openrouter',1000000,1.5,4.5,0.2,'["high", "max"]',0);
INSERT INTO "models" VALUES('zai-org/GLM-5.3','Z.ai','GLM 5.3 High','openrouter',1000000,1.4,4.4,0.26,'["low", "high", "max"]',0);
INSERT INTO "models" VALUES('google/gemma-4-31b-qat','Google','Gemma 4 31B QAT','lmstudio',32768,0.0,0.0,0.0,'["none"]',0);
INSERT INTO "models" VALUES('deepseek/deepseek-v4-pro','Auto','deepseek/deepseek-v4-pro','openrouter',1000000,0.0,0.0,0.0,'["none"]',0);
CREATE TABLE user_configs (
            config_id TEXT PRIMARY KEY,
            device_id TEXT NOT NULL REFERENCES devices(device_id),
            default_harness TEXT NOT NULL,
            default_gateway TEXT NOT NULL,
            default_model TEXT NOT NULL,
            default_reasoning_effort TEXT,
            is_active INTEGER DEFAULT 1,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
INSERT INTO "user_configs" VALUES('cfg-primary-default','primary-macbook-host','deepseek-harness','openrouter','deepseek/deepseek-v4-pro','high',1,'2026-08-23 05:14:09');
CREATE INDEX idx_invocation_device ON invocation_logs(device_id);
CREATE INDEX idx_invocation_harness ON invocation_logs(harness_id);
CREATE INDEX idx_invocation_model ON invocation_logs(model_id);
CREATE INDEX idx_eval_grade ON evaluations(grade);
COMMIT;
