#!/usr/bin/env bash
# proposals-sink.sh — GH-40 Phase 3 scaffolding (no loop yet).
#
# Append Reviewer-proposed rule changes as an operator-sign-off checklist to a target output file
# (normally the relay/transcript file the turn already writes). The human ticks a box and applies the
# change BY HAND — nothing here is auto-applied.
#
# ponytail: this is a formatter + append, not a new store. The relay file is the existing sink; this
# only (a) standardizes a locatable, delimited "Proposed rule changes" block and (b) hard-refuses to
# write into a rule/operator doc, so the sink can never become a self-edit path. Bash 3.2-portable
# (stock macOS) — no mapfile, no ${x,,}.
#
# Usage:
#   printf '%s\n' "proposal one" "proposal two" | proposals-sink.sh <target-file>
#
# Exit: 0 wrote N proposals; 2 target is a protected rule/operator doc (wrote nothing); 3 no proposals.

set -u
TARGET="${1:?usage: proposals-sink.sh <target-file>}"

# Trust boundary (do NOT simplify away): the sink writes proposals, never the rules themselves. Refuse
# any operator/rule doc as a target, so a misconfigured caller can't turn this into a self-edit path.
case "$(basename "$TARGET")" in
  ROUTER.md|AGENTS.md|GUIDING-PRINCIPLES.md|README.md|CLAUDE.md|PDDA.md)
    echo "proposals-sink: refusing to write proposals into a rule/operator doc ($TARGET)" >&2
    exit 2 ;;
esac

PROPOSALS=()
while IFS= read -r line; do
  [ -n "${line//[[:space:]]/}" ] && PROPOSALS+=("$line")
done
[ "${#PROPOSALS[@]}" -gt 0 ] || { echo "proposals-sink: no proposals on stdin" >&2; exit 3; }

{
  echo ""
  echo "<!-- BEGIN PROPOSED RULE CHANGES (operator sign-off required) -->"
  echo "## Proposed rule changes — needs operator sign-off"
  echo "_Generated by the Reviewer. Tick a box and apply it by hand; nothing here is auto-applied._"
  echo ""
  for p in "${PROPOSALS[@]}"; do echo "- [ ] $p"; done
  echo "<!-- END PROPOSED RULE CHANGES -->"
} >> "$TARGET"

echo "proposals-sink: appended ${#PROPOSALS[@]} proposal(s) to $TARGET"
