#!/usr/bin/env bash
# proposals-sink.sh — GH-40 Phase 3 scaffolding (no loop yet).
#
# Append Reviewer-proposed rule changes as an operator-sign-off checklist to a target output file
# (normally the relay/transcript file the turn already writes). The human ticks a box and applies the
# change BY HAND — nothing here is auto-applied.
#
# ponytail: this is a formatter + append, not a new store. The relay file is the existing sink; this
# only (a) standardizes a locatable, delimited "Proposed rule changes" block and (b) hard-refuses to
# write into a rule/operator doc, so the sink can never become a self-edit path. Bash 3.2-portable
# (stock macOS) — no mapfile, no ${x,,}.
#
# Usage:
#   printf '%s\n' "proposal one" "proposal two" | proposals-sink.sh <target-file>
#
# Exit: 0 wrote N proposals; 2 target is a protected rule/operator doc (wrote nothing); 3 no proposals.

set -u
TARGET="${1:?usage: proposals-sink.sh <target-file>}"

# Trust boundary (do NOT simplify away): the sink writes proposals, never the rules themselves. Refuse
# any operator/rule doc as a target, so a misconfigured caller can't turn this into a self-edit path.
# Refuse a SYMLINK target outright — an innocently-named symlink (notes.md -> ROUTER.md) would otherwise
# bypass the basename check and write straight into a rule doc.
if [ -L "$TARGET" ]; then
  echo "proposals-sink: refusing a symlink target ($TARGET) — it could point at a rule/operator doc" >&2
  exit 2
fi
# Match case-INSENSITIVELY: stock macOS/APFS is case-insensitive, so Router.md and ROUTER.md are the
# same file; a case-sensitive match would let Router.md slip through. tr (not bash-4 ${x,,}) keeps 3.2.
TARGET_BASE_LC="$(basename "$TARGET" | tr '[:upper:]' '[:lower:]')"
case "$TARGET_BASE_LC" in
  router.md|agents.md|guiding-principles.md|readme.md|claude.md|pdda.md)
    echo "proposals-sink: refusing to write proposals into a rule/operator doc ($TARGET)" >&2
    exit 2 ;;
esac
# Same-inode (hard-link) check: an innocently-named HARD link (notes.md hard-linked to ROUTER.md) is
# neither a symlink nor a protected basename, yet `>>` lands in the protected doc. `test -ef` compares
# device+inode, so it catches it. Check the protected-name siblings in the target's dir AND the
# canonical repo-root docs (best-effort; skipped outside a git repo).
PROTECTED="ROUTER.md AGENTS.md GUIDING-PRINCIPLES.md README.md CLAUDE.md PDDA.md"
TDIR="$(dirname "$TARGET")"
GROOT="$(git -C "$TDIR" rev-parse --show-toplevel 2>/dev/null || true)"
for name in $PROTECTED; do
  for cand in "$TDIR/$name" ${GROOT:+"$GROOT/$name"}; do
    if [ -e "$cand" ] && [ "$TARGET" -ef "$cand" ]; then
      echo "proposals-sink: target is the same file as a rule/operator doc ($cand) — refusing" >&2
      exit 2
    fi
  done
done

PROPOSALS=()
while IFS= read -r line; do
  [ -n "${line//[[:space:]]/}" ] && PROPOSALS+=("$line")
done
[ "${#PROPOSALS[@]}" -gt 0 ] || { echo "proposals-sink: no proposals on stdin" >&2; exit 3; }

# Verify the append CAN succeed before claiming it did — don't silently lose the Reviewer's proposals
# while reporting success. (Checked explicitly, not via the redirect's exit status: a failed
# redirection on a negated group command does not reliably propagate non-zero on bash 3.2.)
TARGET_DIR="$(dirname "$TARGET")"
[ -d "$TARGET_DIR" ] || { echo "proposals-sink: target directory does not exist ($TARGET_DIR)" >&2; exit 1; }
if [ -e "$TARGET" ]; then
  [ -w "$TARGET" ] || { echo "proposals-sink: target is not writable ($TARGET)" >&2; exit 1; }
else
  [ -w "$TARGET_DIR" ] || { echo "proposals-sink: target directory is not writable ($TARGET_DIR)" >&2; exit 1; }
fi

{
  echo ""
  echo "<!-- BEGIN PROPOSED RULE CHANGES (operator sign-off required) -->"
  echo "## Proposed rule changes — needs operator sign-off"
  echo "_Generated by the Reviewer. Tick a box and apply it by hand; nothing here is auto-applied._"
  echo ""
  for p in "${PROPOSALS[@]}"; do echo "- [ ] $p"; done
  echo "<!-- END PROPOSED RULE CHANGES -->"
} >> "$TARGET"

echo "proposals-sink: appended ${#PROPOSALS[@]} proposal(s) to $TARGET"
